name: Push Event Workflow for Testing

on: push 

jobs:
  unit-testing:
    runs-on: ubuntu-latest 
    
    steps:
    - name : Checkout code
      uses : actions/checkout@v2
      
    # - name : Install Packages 
    #   run : pip install unittest
      
    - name : Run tests 
      run : pytest test_barrierReferralData.py
