name: Push Event Workflow for Testing

on: push 

jobs:
  unit-testing:
    runs-on: ubuntu-latest 
    
    steps:
    - name : Checkout code
      uses : actions/checkout@v2
      
    - name : Install pipenv 
      run : pip install pipenv

    - name : Install dependencies
      run :  pipenv install
      
    - name : Run tests 
      run : pipenv run python test_barrierReferralData.py
